//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamienPapierNozyce_Console {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Statements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Statements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KamienPapierNozyce_Console.Statements", typeof(Statements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Remis..
        /// </summary>
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mamy Remis..
        /// </summary>
        internal static string DrawGame {
            get {
                return ResourceManager.GetString("DrawGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zagrajmy w grę papier, kamień, nożyce. Jeśli chcesz poznać zasady naciśnij &apos;Y&apos;..
        /// </summary>
        internal static string Initialization {
            get {
                return ResourceManager.GetString("Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeśli je znasz i chcesz zacząć rozgywkę naciśnij inny klawisz..
        /// </summary>
        internal static string Initialization2 {
            get {
                return ResourceManager.GetString("Initialization2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moim przedmiotem był .
        /// </summary>
        internal static string ItemStatement {
            get {
                return ResourceManager.GetString("ItemStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Punkt dla mnie..
        /// </summary>
        internal static string Lose {
            get {
                return ResourceManager.GetString("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przegrałeś, powodzenia następnym razem..
        /// </summary>
        internal static string LoseGame {
            get {
                return ResourceManager.GetString("LoseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nie! To pistolet! Wygrywasz całą grę!.
        /// </summary>
        internal static string PistolStatement {
            get {
                return ResourceManager.GetString("PistolStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój wynik to  .
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Mój wynik to .
        /// </summary>
        internal static string Result2 {
            get {
                return ResourceManager.GetString("Result2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wylosowałem przedmiot, teraz twoja kolej (x - nożyce, o - kamień, i -papier), jeśli chcesz zakończyć naciśnij &apos;e&apos;: .
        /// </summary>
        internal static string RoundStart {
            get {
                return ResourceManager.GetString("RoundStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpocznijmy rozgrywkę..
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Będę losował jeden z trzech przedmiotów: kamień (O), papier (I) lub nożyce (X)..
        /// </summary>
        internal static string Tutorial1 {
            get {
                return ResourceManager.GetString("Tutorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następnie nie znając mojego wyboru podaj jeden z przedmiotów poprzez jego skrót: kamień (O), papier (I) lub nożyce (X)..
        /// </summary>
        internal static string Tutorial2 {
            get {
                return ResourceManager.GetString("Tutorial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby mnie pokonać, twój przedmiot musi wygrać z moim na zasadzie: .
        /// </summary>
        internal static string Tutorial3 {
            get {
                return ResourceManager.GetString("Tutorial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nożyce wygrywają z papierem, papier z kamieniem, a kamień z nożycami..
        /// </summary>
        internal static string Tutorial4 {
            get {
                return ResourceManager.GetString("Tutorial4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Będę liczył punkty. Aby zakończyć rozgrywkę wciśnij &apos;e&apos;. Niech moc będzie z Tobą!.
        /// </summary>
        internal static string Tutorial5 {
            get {
                return ResourceManager.GetString("Tutorial5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Punkt dla Ciebie..
        /// </summary>
        internal static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygrałeś, gratuluję!.
        /// </summary>
        internal static string WinGame {
            get {
                return ResourceManager.GetString("WinGame", resourceCulture);
            }
        }
    }
}
